---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>
<br>

# **Curriculum vitae**

<br>

---------

## Education

<br>

**Cornell University**: PhD candidate, Applied Ecology (projected finish: 2023)

**SUNY College of Environmental Science and Forestry**: Master of Science in Ecology (2013)

**Maxwell School of Citizenship at Syracuse University**: Master of Public Administration (2013)

**SUNY College at Brockport**: Bachelor of Science in Environmental Science and Biology (2008)

<br>

------


## Professional Experience 

<br>

#### Cornell University (Ithaca, NY)

**Graduate Research Assistant, Applied Ecology (2019 - present)**

* Using long-term monitoring datasets to understand the lower trophic levels of the Great Lakes
* Launched a Zooplankton as Indicators project in Nov 2019 (>100 participants from 28 countries) as part of the Global Lake Ecological Observatory Network to investigate the use of zooplankton as indicators with a global dataset

<br>

#### USEPA, Office of Research and Development (Narragansett, RI)

**Oak Ridge Institute of Science and Education Research Participant (2015 - 2019)**

* Determined the impact of impervious cover on macroinvertebrate communities in intermittent and perennial streams using Threshold Indicator Taxa ANalysis in R and introduced a statistical R package, pTITAN2
*	Developed a Spatial Statistical Network stream temperature model to guide the Houlton Band of Maliseet Indians riparian restoration priorities by predicting several restoration scenarios using four restored riparian buffer widths ([published](http://www.sciencedirect.com/science/article/pii/S0301479720315103))
 
<br>

#### Wissahickon Trails (former Wissahickon Valley Watershed Association, Ambler, PA)

**Water Quality Program Manager (2014 - 2015)**

*	Team leader and program manager of a $143K/year Delaware River Watershed Initiative (DRWI) grant
*	Expanded an existing water quality program by (1) improving the statistical quality of data by implementing a QA/QC plan, (2) bolstering sampling at restoration sites to quantify improvements, and (3) leading the DWRI water quality sub-committee and implementing monitoring plans, QA/QC practices, and developing a water quality database for four partner watershed organizations

**Independent Contractor (2016 - 2017)**

*	Quantified trends in habitat, macroinvertebrate, and water quality with over a decade of monitoring data
*	Summarized findings for public, municipalities, and scientific audiences in a white paper (92 pages)

<br>

#### SUNY ESF (Syracuse, NY)

**Graduate Research Assistant, Ecology (2009 - 2011)**

* Investigated invertebrate dispersal to newly created vernal pools in an experimental forest (39 ponds) and survey ponds (40 ponds) surrounding the experimental forest ([published](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.1377))
*	Led field sampling, analyzed water chemistry, created a database, and identified invertebrates 

**Graduate Teaching Assistant (2011 - 2012)**

* Taught upper level courses: Marine Ecology (~100 students) and Limnology (~80 students)
*	Led weekly lecture presentations on ecological concepts, organisms, and foundation water quality sampling and laboratory methods


<br>

#### Clarkson University (Potsdam, NY)

**Research Technician, Limnology (2009)**

* Determined the accuracy and precision of aquatic research equipment, the bbe FluoroProbe® ([published](https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2013-0599))


<br>

#### Research Foundation (Brockport, NY)

**Research Technician, Limnology (2007 - 2008)**

* Analyzed water quality samples following Standard Operating Procedures, maintaining laboratory databases, and insuring Quality Assurance/Quality Control practices in accordance to NELAC


<br>

------

## Awards and Successful Grant Applications

* IAGLR David M. Dolan Quantitative Ecology [Scholarship](http://iaglr.org/awards-scholarships/dolan-scholarship/). 2021.
* Serve-in-Place. 2021. $700. [Vaccination Conversations with Scientists.](https://gradcareers.cornell.edu/opportunities/vaccination-conversations-with-scientists-vacs/) 
* WVWA. Growing Greener. 2015. $369,600. Stream restoration.
* WVWA. William Penn Foundation. 2015. $82,500. Stakeholder collaboration.
* WVWA. National Fish and Wildlife Foundation. 2015. $190,000. Restoration construction plans.
* SUNY ESF. Seven grants totaling $8500 for research and travel funds.

<br>

------

## Professional Societies

* Association for the Sciences of Limnology and Oceanography
* Ecological Society of America
* Society for Freshwater Science
* Global Lake Ecological Observatory Network
* International Association for Great Lakes Research


<br>

------

## Certifications and Workshops

* Communications Boot Camp for Scientists. American Institute of Biological Sciences. Washington, D.C. (2017)
* Certified Wetland Delineator, Rutgers University 
* Open Water Dive and Dry Suit Certified
* New York Boater Safety Course


<br>