---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>
<br>

## Public Service

I'm passionate about bringing research and scientific knowledge into public service. Since 2014, I have served on town Conservation Commissions or Natural Resource boards. Here, I have been active in several projects including delineating a wetland to develop a new trail system in Narragansett, RI, creating a land management plan for an emerging salt marsh, and now tackling deer management in the natural lands in the City of Ithaca. 

<br>

* **City of Ithaca Parks, Recreation and Natural Resources Commission**, member (appointment: 2019 - present)
* **Narragansett Conservation Commission**, Vice Chair (appointment: 2016 - 2019)
  * Middlebridge Conservation Plan Working Group
* **Ambler Environmental Advisory Council**, member (appointment: 2014 - 2015)

I am always looking for new ways to merge my research interests with public service. Please reach out if you have any opportunities.

<br>

## Other Interests

I'm an avid hiker, runner, kayaker, and yogi. When I'm not working on my research, I'm likely spending time with friends or my niece and nephews,  listening to too many podcasts, or attempting to improve my poor art skills.