---
output: html_document
title: Publications
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

### **Published journal articles**

**Figary, S. E.**, K. Holeck, C. Hotaling, J. Watkins, J. Lantry, M. Connerton, S. Prindle, Z. Biesinger, B. O’Malley, L. Rudstam. 2023. Lake Ontario’s nearshore zooplankton: Community composition changes and comparisons to the offshore. Journal of Great Lakes Research. In press. [Read](https://doi.org/10.1016/j.jglr.2023.02.013).

Jordan, P. D. B., **S. E. Figary**, T. E. Brooking, K. T. Holeck, C. W. Hotaling, A. J. VanDeValk, L. G. Rudstam. 2023. The effects of *Bythotrephes longimanus* invasion on diets and growth of age-0 yellow perch in Oneida Lake, New York. Ecology of Freshwater Fish. In press. [Read](https://doi.org/10.1111/eff.12717).

**Figary, S. E.**, M. F. Meyer, W. J. S. Currie, and ZIG Participants. 2022. Building a worldwide freshwater zooplankton dataset to synthesis patterns of zooplankton community structure and change.  Limnology and Oceanography Bulletin. Community News. [Read](https://doi.org/10.1002/lob.10515).

**Figary, S. E.** and K. L. Schulz. 2021 Spines and surplus: Existing inducible defenses and abundant resources may reduce the impacts of *Cercopagis pengoi* on a likely prey species. Aquatic Invasions. 16(3): 461–481, 2021.16.3.05. [Read](https://doi.org/10.3391/ai).

**Figary, S.,** N. Detenbeck, and C. O'Donnell. 2021. Guiding riparian management in a transboundary watershed through high resolution spatial statistical network models. Journal of Environmental Management. 278(2): 111585. [Read](https://doi.org/10.1016/j.jenvman.2020.111585).

Holmes, C. J., **S. Figary,** K. L. Schulz, and C. E. Cáceres. 2016. Effects of diversity on community assembly in newly formed pond communities. Ecosphere 7(7): e01377. [Read](https://doi.org/10.1002/ecs2.1377)

Kring, S. A., **S. E. Figary,** G. L. Boyer, S. B. Watson, and M. R. Twiss. 2014. Rapid in situ measures of phytoplankton communities using the bbe FluoroProbe®: Evaluation of spectral calibration, instrument intercompatibility and performance range. Canadian Journal of Fisheries and Aquatic Sciences, 71(7): 1087-1095.  [Read](https://doi.org/10.1139/cjfas-2013-0599)


<br>

### **Manuscripts in preparation**

Kovalenko K., E. D. Reavie, **S. Figary**, L. G. Rudstam, J. M. Watkins, A. Scofield, C. T. Filstrup. Zooplankton-phytoplankton biomass and diversity relationships in the Great Lakes. PLOS ONE. (under review)

**Figary, S.**, P. DeWitt and N. Detenbeck. pTITAN2: Permutation of Treatment Labels and Threshold Indicator Taxa ANalysis. F1000Research. [In open review](https://f1000research.com/articles/11-267/pdf)

**Figary, S.** and N. Detenbeck. Resolution matters: macroinvertebrate responses to impervious cover in a Mediterranean differs with impervious cover datasets. Freshwater Science. (in prep)

<br>

### **Reports**

**Figary, S.** 2017. Wissahickon Watershed Stream Monitoring and Assessment Program: A summary of data collected by the *Wissahickon Valley Watershed Association* from 2004-2016. [Executive Report](https://wissahickontrails.org/uploads/attachments/ck7ouwd5d020jio4l7vsir9ah-streammonitoringreport.pdf)

Begay, J., T. Dannan, K. M. Edwards, **S. Figary.** 2012. Economic impact analysis of Onondaga County’s green infrastructure program, *Save the Rain*. Executive Report. [Read](https://issuu.com/savetherain/docs/save_the_rain_economic_impact_report_final)